### ISSUE TITLE
Compute Module 4 as a unique component

### ISSUE THREAD

**Issue by estevaofv** [QWaveSystems/QWAVE_Raspberry-Pi-CM4-Altium-Library#1]
;Hello, first of all thanks for sharing! 

We made a very similar thing as you importing the compute module 4 to Altium, as one component, but after some thought we find some possible problems: 
- How to get the exact reference and coordinates for the 2 connectors that will be used to plug the CM4 to the base board? I'm referring to the receptacle connector (DF40C-100DS-0.4V(51)) how to find and define their individual coordinates since we use two per boards and the reference is in the center of the CM4 as in the picture:

![image](https://user-images.githubusercontent.com/12235551/98261039-c8242480-1f62-11eb-965f-4d04b65f096e.png)

- Also is there a way to work with Altium besides to manually insert the DF40C-100DS-0.4V(51) in the BOM, since for each CM4 in the BOM we will need 2 x DF40C-100DS-0.4V(51) connectors?

Do these points make sense? How did you plan to face this situation?
What we are planning to do is to "break" the CM4 in 2 parts associating each half with one DF40C-100DS-0.4V(51) connector, so we will have its exactly center coordinate that will be used in the assembly 

![image](https://user-images.githubusercontent.com/12235551/98262185-12f26c00-1f64-11eb-92c0-efcaa25e887b.png)

and the hard part will be to match the exact distance and alignment of the two separate connectors to match the CM4, we will do it based on the footprints imported from KIcad. Do you think this approach makes sense for you?

Thanks in advance and thanks one more time for sharing!

**Comment by Amornthep-Phunsin** [comment]
I got your point and thanks for raise this issue up, 

1. Base on physical dimension page 4 as this link you can find exectly dimension or got them form STEP file.
[https://datasheets.raspberrypi.org/cm4/cm4-product-brief.pdf](https://datasheets.raspberrypi.org/cm4/cm4-product-brief.pdf)

2.I agreed with you if imported to Altium as single component, it is required to manually edit BOM list to added 2xconnector. 
Agreed that your solution should solved this by break to 2 component, the one for Low speed another one for highspeed, I would suggest added one more PCB compont as connector guideline in Mech layer, (*use this only for alignment position of both connectors)
