### ISSUE TITLE
Pick & Place

### ISSUE THREAD

**Issue by WayneManoni** [QWaveSystems/QWAVE_Raspberry-Pi-CM4-Altium-Library#3]
Only 1 pick and place location is generated and component requires 2 connectors.

**Comment by Amornthep-Phunsin** [comment]
1. At CM4 Schematic sheet at Property > General > Type > set to Standard (NO BOM)
2. Add J1,J2 for DF40 connector with dummy footprint place at center of actual connector location.

![image](https://user-images.githubusercontent.com/12686721/145389361-baa84514-95e2-4904-a11f-88b681e3640d.png)

![image](https://user-images.githubusercontent.com/12686721/145389410-ed7a4ebf-10a6-4cd4-b5cc-7b2c7bc6f965.png)

**Comment by lelsteph** [comment]
Hello

Thank you very much! I have a comment / clarification.

So we need to first use CM4-DF40HC(3.0)-100DS-0.4v_3mm_1.5mm_NO_Outline as it seems it is the only one having the center of the connectors?

![image](https://user-images.githubusercontent.com/28821262/227526213-881e0bda-2f14-4bcc-b4cc-c0a869b47b10.png)

Then once the 2 pads are positioned, we can change it to CM4-DF40HC(3.0)-100DS-0.4v_3mm_1.5mm to get the 3D and complete footprint?

Thank you very much!

Stephane.
