### ISSUE TITLE
High and low question

### ISSUE THREAD

**Issue by ahmadfarisfs** [QWaveSystems/QWAVE_Raspberry-Pi-CM4-Altium-Library#4]
Hi first of all thank for sharing this amazing work! I have question regarding the high and low you mentioned here. What does that mean ? maybe you could add more information on the schematic as well ? Thank you in advance

![image](https://user-images.githubusercontent.com/17040286/175222245-5c9e8707-421c-4516-b701-6ff5d45cdf8b.png)

**Comment by Amornthep-Phunsin** [comment]
there are default pin state of original RPI GPIO driver.
